name: Update README

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Go program
        run: |
          cd ${GITHUB_WORKSPACE}  # Change directory to workspace
          go run main.go          # Run your Go program

      - name: Add and commit changes (if any)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Update README.md" || true  # Commit only if there are changes

      - uses: actions/checkout@v3
