name: Update README

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - name: Run Go program
        run: |
          cd ${GITHUB_WORKSPACE}
          go run main.go

      - uses: stefanzweifel/git-auto-commit-action@v5
